import {Router} from 'express';
import * as controller from './billing.controller.js';
import {protect} from '../../middlewares/auth.middleware.js';
const router=Router();
router.use(protect);
router.post('/accounts',controller.createBillingAccount);
router.get('/accounts/:id',controller.getBillingAccount);
router.get('/patients/:patientId/account',controller.getPatientBillingAccount);
router.get('/patients/:patientId',controller.getPatientBilling);
router.post('/catalogue',controller.createPricingCatalogueItem);
router.get('/catalogue',controller.getPricingCatalogue);
router.patch('/catalogue/:id',controller.updatePricingCatalogueItem);
router.post('/charges',controller.createCharge);
router.get('/charges',controller.getCharges);
router.post('/payments',controller.createPayment);
router.get('/payments',controller.getPayments);
router.patch('/payments/:id/reconcile',controller.reconcilePayment);
router.post('/refunds',controller.createRefund);
router.patch('/refunds/:id/decision',controller.decideRefund);
router.post('/refunds/:id/complete',controller.completeRefund);
router.post('/payment-plans',controller.createPaymentPlan);
export default router;